# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/System1080p/System1080p.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p || ORIG_REF_NAME==System1080p}]

# IP: bd/System1080p/ip/System1080p_imageProcess_0_0/System1080p_imageProcess_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p_imageProcess_0_0 || ORIG_REF_NAME==System1080p_imageProcess_0_0}]

# IP: bd/System1080p/ip/System1080p_imageProcess_0_0/ip/outputBuffer/outputBuffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer}]

# IP: bd/System1080p/ip/System1080p_imageProcess_0_0/ip/div_gen_0/div_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0}]

# IP: bd/System1080p/ip/System1080p_processing_system7_0_0/System1080p_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p_processing_system7_0_0 || ORIG_REF_NAME==System1080p_processing_system7_0_0}]

# IP: bd/System1080p/ip/System1080p_axi_dma_0_0/System1080p_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p_axi_dma_0_0 || ORIG_REF_NAME==System1080p_axi_dma_0_0}]

# IP: bd/System1080p/ip/System1080p_processing_system7_0_axi_periph_0/System1080p_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==System1080p_processing_system7_0_axi_periph_0}]

# IP: bd/System1080p/ip/System1080p_rst_processing_system7_0_100M_0/System1080p_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System1080p_rst_processing_system7_0_100M_0}]

# IP: bd/System1080p/ip/System1080p_axi_mem_intercon_0/System1080p_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p_axi_mem_intercon_0 || ORIG_REF_NAME==System1080p_axi_mem_intercon_0}]

# IP: bd/System1080p/ip/System1080p_xbar_0/System1080p_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p_xbar_0 || ORIG_REF_NAME==System1080p_xbar_0}]

# IP: bd/System1080p/ip/System1080p_axis_dwidth_converter_0_0/System1080p_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p_axis_dwidth_converter_0_0 || ORIG_REF_NAME==System1080p_axis_dwidth_converter_0_0}]

# IP: bd/System1080p/ip/System1080p_xlconcat_0_0/System1080p_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p_xlconcat_0_0 || ORIG_REF_NAME==System1080p_xlconcat_0_0}]

# IP: bd/System1080p/ip/System1080p_auto_pc_0/System1080p_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p_auto_pc_0 || ORIG_REF_NAME==System1080p_auto_pc_0}]

# IP: bd/System1080p/ip/System1080p_auto_pc_1/System1080p_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p_auto_pc_1 || ORIG_REF_NAME==System1080p_auto_pc_1}]

# IP: bd/System1080p/ip/System1080p_auto_us_0/System1080p_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p_auto_us_0 || ORIG_REF_NAME==System1080p_auto_us_0}]

# IP: bd/System1080p/ip/System1080p_auto_us_1/System1080p_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System1080p_auto_us_1 || ORIG_REF_NAME==System1080p_auto_us_1}]

# XDC: bd/System1080p/ip/System1080p_imageProcess_0_0/ip/outputBuffer/outputBuffer/outputBuffer.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer}] {/U0 }]/U0 ]]

# XDC: bd/System1080p/ip/System1080p_imageProcess_0_0/ip/outputBuffer/outputBuffer_ooc.xdc

# XDC: bd/System1080p/ip/System1080p_imageProcess_0_0/ip/div_gen_0/div_gen_0_ooc.xdc

# XDC: bd/System1080p/ip/System1080p_processing_system7_0_0/System1080p_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System1080p_processing_system7_0_0 || ORIG_REF_NAME==System1080p_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/System1080p/ip/System1080p_axi_dma_0_0/System1080p_axi_dma_0_0_ooc.xdc

# XDC: bd/System1080p/ip/System1080p_axi_dma_0_0/System1080p_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System1080p_axi_dma_0_0 || ORIG_REF_NAME==System1080p_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System1080p/ip/System1080p_axi_dma_0_0/System1080p_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System1080p_axi_dma_0_0 || ORIG_REF_NAME==System1080p_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System1080p/ip/System1080p_rst_processing_system7_0_100M_0/System1080p_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System1080p_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System1080p_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/System1080p/ip/System1080p_rst_processing_system7_0_100M_0/System1080p_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System1080p_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System1080p_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/System1080p/ip/System1080p_rst_processing_system7_0_100M_0/System1080p_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/System1080p/ip/System1080p_xbar_0/System1080p_xbar_0_ooc.xdc

# XDC: bd/System1080p/ip/System1080p_axis_dwidth_converter_0_0/System1080p_axis_dwidth_converter_0_0_ooc.xdc

# XDC: bd/System1080p/ip/System1080p_auto_pc_0/System1080p_auto_pc_0_ooc.xdc

# XDC: bd/System1080p/ip/System1080p_auto_pc_1/System1080p_auto_pc_1_ooc.xdc

# XDC: bd/System1080p/ip/System1080p_auto_us_0/System1080p_auto_us_0_ooc.xdc

# XDC: bd/System1080p/ip/System1080p_auto_us_0/System1080p_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System1080p_auto_us_0 || ORIG_REF_NAME==System1080p_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/System1080p/ip/System1080p_auto_us_1/System1080p_auto_us_1_ooc.xdc

# XDC: bd/System1080p/ip/System1080p_auto_us_1/System1080p_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System1080p_auto_us_1 || ORIG_REF_NAME==System1080p_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/System1080p/System1080p_ooc.xdc
